export const nationality = [
	{ name: "Afghanistan" },
	{ name: "Albania" },
	{ name: "Antarctica" },
	{ name: "Algeria" },
	{ name: "American Samoa" },
	{ name: "Andorra" },
	{ name: "Angola" },
	{ name: "Antigua and Barbuda" },
	{ name: "Azerbaijan" },
	{ name: "Argentina" },
	{ name: "Australia" },
	{ name: "Austria" },
	{ name: "Bahamas" },
	{ name: "Bahrain" },
	{ name: "Bangladesh" },
	{ name: "Armenia" },
	{ name: "Barbados" },
	{ name: "Belgium" },
	{ name: "Bermuda" },
	{ name: "Bhutan" },
	{ name: "Bolivia}, Plurinational State of" },
	{ name: "Bosnia and Herzegovina" },
	{ name: "Botswana" },
	{ name: "Bouvet Island" },
	{ name: "Brazil" },
	{ name: "Belize" },
	{ name: "British Indian Ocean Territory" },
	{ name: "Solomon Islands" },
	{ name: "Virgin Islands}, British" },
	{ name: "Brunei Darussalam" },
	{ name: "Bulgaria" },
	{ name: "Myanmar" },
	{ name: "Burundi" },
	{ name: "Belarus" },
	{ name: "Cambodia" },
	{ name: "Cameroon" },
	{ name: "Canada" },
	{ name: "Cabo Verde" },
	{ name: "Cayman Islands" },
	{ name: "Central African Republic" },
	{ name: "Sri Lanka" },
	{ name: "Chad" },
	{ name: "Chile" },
	{ name: "China" },
	{ name: "Taiwan}, Province of China" },
	{ name: "Christmas Island" },
	{ name: "Cocos (Keeling) Islands" },
	{ name: "Colombia" },
	{ name: "Comoros" },
	{ name: "Mayotte" },
	{ name: "Congo" },
	{ name: "Congo}, the Democratic Republic of the" },
	{ name: "Cook Islands" },
	{ name: "Costa Rica" },
	{ name: "Croatia" },
	{ name: "Cuba" },
	{ name: "Cyprus" },
	{ name: "Czech Republic" },
	{ name: "Benin" },
	{ name: "Denmark" },
	{ name: "Dominica" },
	{ name: "Dominican Republic" },
	{ name: "Ecuador" },
	{ name: "El Salvador" },
	{ name: "Equatorial Guinea" },
	{ name: "Ethiopia" },
	{ name: "Eritrea" },
	{ name: "Estonia" },
	{ name: "Faroe Islands" },
	{ name: "Falkland Islands (Malvinas)" },
	{ name: "South Georgia and the South Sandwich Islands" },
	{ name: "Fiji" },
	{ name: "Finland" },
	{ name: "Åland Islands" },
	{ name: "France" },
	{ name: "French Guiana" },
	{ name: "French Polynesia" },
	{ name: "French Southern Territories" },
	{ name: "Djibouti" },
	{ name: "Gabon" },
	{ name: "Georgia" },
	{ name: "Gambia" },
	{ name: "Palestine}, State of" },
	{ name: "Germany" },
	{ name: "Ghana" },
	{ name: "Gibraltar" },
	{ name: "Kiribati" },
	{ name: "Greece" },
	{ name: "Greenland" },
	{ name: "Grenada" },
	{ name: "Guadeloupe" },
	{ name: "Guam" },
	{ name: "Guatemala" },
	{ name: "Guinea" },
	{ name: "Guyana" },
	{ name: "Haiti" },
	{ name: "Heard Island and McDonald Islands" },
	{ name: "Holy See (Vatican City State)" },
	{ name: "Honduras" },
	{ name: "Hong Kong" },
	{ name: "Hungary" },
	{ name: "Iceland" },
	{ name: "India" },
	{ name: "Indonesia" },
	{ name: "Iran}, Islamic Republic of" },
	{ name: "Iraq" },
	{ name: "Ireland" },
	{ name: "Israel" },
	{ name: "Italy" },
	{ name: "Côte d`Ivoire" },
	{ name: "Jamaica" },
	{ name: "Japan" },
	{ name: "Kazakhstan" },
	{ name: "Jordan" },
	{ name: "Kenya" },
	{ name: "Korea}, Democratic People`s Republic of" },
	{ name: "Korea}, Republic of" },
	{ name: "Kuwait" },
	{ name: "Kyrgyzstan" },
	{ name: "Lao People`s Democratic Republic" },
	{ name: "Lebanon" },
	{ name: "Lesotho" },
	{ name: "Latvia" },
	{ name: "Liberia" },
	{ name: "Libya" },
	{ name: "Liechtenstein" },
	{ name: "Lithuania" },
	{ name: "Luxembourg" },
	{ name: "Macao" },
	{ name: "Madagascar" },
	{ name: "Malawi" },
	{ name: "Malaysia" },
	{ name: "Maldives" },
	{ name: "Mali" },
	{ name: "Malta" },
	{ name: "Martinique" },
	{ name: "Mauritania" },
	{ name: "Mauritius" },
	{ name: "Mexico" },
	{ name: "Monaco" },
	{ name: "Mongolia" },
	{ name: "Moldova}, Republic of" },
	{ name: "Montenegro" },
	{ name: "Montserrat" },
	{ name: "Morocco" },
	{ name: "Mozambique" },
	{ name: "Oman" },
	{ name: "Namibia" },
	{ name: "Nauru" },
	{ name: "Nepal" },
	{ name: "Netherlands" },
	{ name: "Curaçao" },
	{ name: "Aruba" },
	{ name: "Sint Maarten (Dutch part)" },
	{ name: "Bonaire}, Sint Eustatius and Saba" },
	{ name: "New Caledonia" },
	{ name: "Vanuatu" },
	{ name: "New Zealand" },
	{ name: "Nicaragua" },
	{ name: "Niger" },
	{ name: "Nigeria" },
	{ name: "Niue" },
	{ name: "Norfolk Island" },
	{ name: "Norway" },
	{ name: "Northern Mariana Islands" },
	{ name: "United States Minor Outlying Islands" },
	{ name: "Micronesia}, Federated States of" },
	{ name: "Marshall Islands" },
	{ name: "Palau" },
	{ name: "Pakistan" },
	{ name: "Panama" },
	{ name: "Papua New Guinea" },
	{ name: "Paraguay" },
	{ name: "Peru" },
	{ name: "Philippines" },
	{ name: "Pitcairn" },
	{ name: "Poland" },
	{ name: "Portugal" },
	{ name: "Guinea-Bissau" },
	{ name: "Timor-Leste" },
	{ name: "Puerto Rico" },
	{ name: "Qatar" },
	{ name: "Réunion" },
	{ name: "Romania" },
	{ name: "Russian Federation" },
	{ name: "Rwanda" },
	{ name: "Saint Barthélemy" },
	{ name: "Saint Helena}, Ascension and Tristan da Cunha" },
	{ name: "Saint Kitts and Nevis" },
	{ name: "Anguilla" },
	{ name: "Saint Lucia" },
	{ name: "Saint Martin (French part)" },
	{ name: "Saint Pierre and Miquelon" },
	{ name: "Saint Vincent and the Grenadines" },
	{ name: "San Marino" },
	{ name: "Sao Tome and Principe" },
	{ name: "Saudi Arabia" },
	{ name: "Senegal" },
	{ name: "Serbia" },
	{ name: "Seychelles" },
	{ name: "Sierra Leone" },
	{ name: "Singapore" },
	{ name: "Slovakia" },
	{ name: "Viet Nam" },
	{ name: "Slovenia" },
	{ name: "Somalia" },
	{ name: "South Africa" },
	{ name: "Zimbabwe" },
	{ name: "Spain" },
	{ name: "South Sudan" },
	{ name: "Sudan" },
	{ name: "Western Sahara" },
	{ name: "Suriname" },
	{ name: "Svalbard and Jan Mayen" },
	{ name: "Swaziland" },
	{ name: "Sweden" },
	{ name: "Switzerland" },
	{ name: "Syrian Arab Republic" },
	{ name: "Tajikistan" },
	{ name: "Thailand" },
	{ name: "Togo" },
	{ name: "Tokelau" },
	{ name: "Tonga" },
	{ name: "Trinidad and Tobago" },
	{ name: "United Arab Emirates" },
	{ name: "Tunisia" },
	{ name: "Turkey" },
	{ name: "Turkmenistan" },
	{ name: "Turks and Caicos Islands" },
	{ name: "Tuvalu" },
	{ name: "Uganda" },
	{ name: "Ukraine" },
	{ name: "Macedonia}, the former Yugoslav Republic of" },
	{ name: "Egypt" },
	{ name: "United Kingdom" },
	{ name: "Guernsey" },
	{ name: "Jersey" },
	{ name: "Isle of Man" },
	{ name: "Tanzania}, United Republic of" },
	{ name: "United States of America" },
	{ name: "Virgin Islands}, U.S." },
	{ name: "Burkina Faso" },
	{ name: "Uruguay" },
	{ name: "Uzbekistan" },
	{ name: "Venezuela}, Bolivarian Republic of" },
	{ name: "Wallis and Futuna" },
	{ name: "Samoa" },
	{ name: "Yemen" },
	{ name: "Zambia" },
];
